# Generated by Django 3.2.8 on 2021-10-23 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('period', '0003_remove_period_category'),
        ('budget', '0002_remove_budget_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category'),
        ),
        migrations.AddField(
            model_name='budget',
            name='period',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='period.period'),
            preserve_default=False,
        ),
    ]
