# Generated by Django 3.2.8 on 2021-10-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20211023_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='remaining',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
