# Generated by Django 3.2.8 on 2021-10-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_budget_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='remaining',
            field=models.IntegerField(default=models.IntegerField(), null=True),
        ),
    ]
