# Generated by Django 3.2.8 on 2021-10-23 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('period', '0002_auto_20211023_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='category',
        ),
    ]
