# Generated by Django 3.2.8 on 2021-10-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_alter_revenue_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
