# Generated by Django 3.2.8 on 2021-10-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0004_alter_revenue_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
