# Generated by Django 3.2.8 on 2021-10-22 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0005_alter_revenue_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='budget_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
