# Generated by Django 3.2.8 on 2021-10-25 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('period', '0003_remove_period_category'),
        ('revenue', '0006_revenue_budget_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='period',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='period.period'),
            preserve_default=False,
        ),
    ]
