# Generated by Django 3.2.8 on 2021-10-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0007_revenue_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='budget_date',
        ),
    ]
