# Generated by Django 3.2.8 on 2021-10-23 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_auto_20211022_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='budget_date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
    ]
